title: Pedro Magalhães # your name (or website title) here
logo: "/images/pedrom.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Estudante Finalista de Engenharia Informática
  <br><br>
  Instituto Politécnico de Leiria
  <br><br>
  <a href="https://www.linkedin.com/in/pedromagalh%C3%A3es/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
